name: Flutter Web Deployment
on:
  push:
    branches:
      - master
      - 'release/*'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      # Copied from https://github.com/erickzanardo/flutter-gh-pages
      - run: flutter config --enable-web
        shell: bash
        working-directory: .
      - run: flutter pub get
        shell: bash
        working-directory: .
      - run: flutter build web --release --web-renderer=auto
        shell: bash
        working-directory: .
      - run: echo "sml2.schnack.dev" > ./build/web/CNAME
        shell: bash
        working-directory: .
      - run: git config user.name github-actions
        shell: bash
        working-directory: .
      - run: git config user.email github-actions@github.com
        shell: bash
        working-directory: .
      - run: git --work-tree build/web add --all
        shell: bash
        working-directory: .
      - run: git commit -m "Automatic deployment by github-actions"
        shell: bash
        working-directory: .
      - run: git push origin HEAD:gh-pages --force
        shell: bash
        working-directory: .
